site_name: 我的自动化文档作品集
theme:
  name: material
  language: zh  # 设置为中文
  features:
    - navigation.tabs # 顶部导航栏
    - search.highlight # 搜索高亮

# 告诉 MkDocs 要用 Mermaid 画图
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 首页: index.md
  - Kernel Space:
    - 01 自动化流水线: 01-automation.md
    - 02 芯片数据手册重构: 02-hardware.md
    - 03 IoT 接口文档: 03-api.md
  - 快速开始: install.md # 对应 docs/install.md
  - 风格指南: style-guide.md